project_id = "grpzbxwafkcvecphnyyb"

[functions]
  [functions.admin-users]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.public-onboarding]
    verify_jwt = false
  [functions.admin-set-user-password]
    verify_jwt = false
  [functions.admin-delete-organization]
    verify_jwt = false
